services:
  localstack:
    image: localstack/localstack
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: us-east-1
      USER_CLIENT: ${USER_CLIENT}
      USER_PASSWORD: ${USER_PASSWORD}
    ports:
      - "4566:4566"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./localstack-setup.sh:/etc/localstack/init/ready.d/script.sh
    healthcheck:
      test:
        "
          curl -X 'GET' \
            'http://localhost.localstack.cloud:4566/_localstack/health' \
            -H 'accept: application/json'
        "